#!/usr/bin/env bash
# Qwen3.5-35B-A3B model-specific Chunk-SAE pipeline entrypoint.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

if (( $# > 1 )); then
  echo "Usage: bash $0 [all|corpus|cache|train|eval]" >&2
  exit 2
fi
[[ $# -eq 0 ]] || export PIPELINE_STAGE="$1"

export MODEL_SIZE="35b-a3b"
export MODEL="${MODEL:-${REPO_ROOT}/models/Qwen3.5-35B-A3B-Base}"
export MODEL_NAME="${MODEL_NAME:-qwen35-35b-a3b-base}"
export NUM_LAYERS="${NUM_LAYERS:-40}"
export LAYER="${LAYER:-26}"
export SAE_MODES="${SAE_MODES:-token,temporal,mean,cross}"
export ATTAINABLE_REFERENCE_FVES="${ATTAINABLE_REFERENCE_FVES:-token=1.0,temporal=1.0,mean=1.0}"
export TEMPORAL_HIGH_FRACTION="${TEMPORAL_HIGH_FRACTION:-0.2}"
export TEMPORAL_HIGH_RECONSTRUCTION_WEIGHT="${TEMPORAL_HIGH_RECONSTRUCTION_WEIGHT:-0.2}"
export TEMPORAL_FULL_RECONSTRUCTION_WEIGHT="${TEMPORAL_FULL_RECONSTRUCTION_WEIGHT:-0.8}"
export TEMPORAL_ALPHA="${TEMPORAL_ALPHA:-1.0}"
export TEMPORAL_TEMPERATURE="${TEMPORAL_TEMPERATURE:-0.1}"
export TEMPORAL_CONTRASTIVE_BLOCK_SIZE="${TEMPORAL_CONTRASTIVE_BLOCK_SIZE:-1024}"

# The MoE checkpoint leaves much less staging headroom than 2B/9B.
export FORWARD_BATCH_SIZE="${FORWARD_BATCH_SIZE:-64}"
export FORWARD_TOKEN_BUDGET="${FORWARD_TOKEN_BUDGET:-32768}"
export STREAM_SCHEDULER_WINDOW_PAIRS="${STREAM_SCHEDULER_WINDOW_PAIRS:-2048}"
export WRITER_BATCH_TOKENS="${WRITER_BATCH_TOKENS:-65536}"
export CACHE_SHARD_TOKENS="${CACHE_SHARD_TOKENS:-65536}"
export ASYNC_WRITE_BATCHES="${ASYNC_WRITE_BATCHES:-2}"
export SHARD_WRITE_WORKERS="${SHARD_WRITE_WORKERS:-2}"
export MAX_PENDING_SHARDS="${MAX_PENDING_SHARDS:-2}"

export LOADER_PREFETCH_SHARDS="${LOADER_PREFETCH_SHARDS:-8}"
export LOADER_PREFETCH_WORKERS="${LOADER_PREFETCH_WORKERS:-2}"
export LOADER_PREFETCH_BATCHES="${LOADER_PREFETCH_BATCHES:-4}"
export LOADER_GPU_SHARDS="${LOADER_GPU_SHARDS:-8}"

export EVIDENCE_FORWARD_BATCH_SIZE="${EVIDENCE_FORWARD_BATCH_SIZE:-8}"
export PROBE_BATCH_SIZE="${PROBE_BATCH_SIZE:-8}"

source "${REPO_ROOT}/src/train_chunk_saes_common.sh"
